spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/coinapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
  sql:
    init:
      mode: never
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true